server:
  port: 8888
spring:
  application:
    name: microservice_config_server
   # INTEGRANDO O SPRING CLOUD CONFIG SERVER COM GITHUB
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JoseLuiz18Bd/microservice_config_server
          #username: user_name
          #password: password
          default-label: main
          search-paths:
          - 'greeting-service*'