spring:
  application:
    name: greeting-service
# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

greeting-service:
  greeting: "Pronto"
  default-value: "Mondo!"